import 'package:challenge02_fteam/src/models/pets_adopt_model.dart';
import 'package:flutter/material.dart';

List<PetsAdoptModel> petsDataList = [
  PetsAdoptModel(
    name: 'Spark',
    location: '2.5 Kms away',
    race: 'Golden Retriever',
    age: '8 months old',
    sex: 'Female',
    photos: [
      'images/Animals/dogs/Golden_retriever/1.png',
      'images/Animals/dogs/Golden_retriever/2.png',
      'images/Animals/dogs/Golden_retriever/3.png',
      'images/Animals/dogs/Golden_retriever/4.png',
      'images/Animals/dogs/Golden_retriever/5.png',
      'images/Animals/dogs/Golden_retriever/6.png',
    ],
    description: 'Of British origin, known for being very docile and companion, the Golden Retriever is considered by many to be the “dream dog”. Quite intelligent, ready to learn tricks and often used as guide dogs, the Golden is an active dog that likes to help and please everyone (including those he doesn t know so well). He loves tricks and needs a lot of attention and free time to spend his energy. He is also a great swimmer and a favorite of several families, something that has made his popularity very high in recent decades here in Brazil and around the world.',
    cor: const Color.fromARGB(255, 252, 237, 37),
  ),
  PetsAdoptModel(
    name: 'Charlie',
    location: '2.6 Kms away',
    race: 'Boston terrier',
    age: '1,5 years old',
    sex: 'Male',
    photos: [
      'images/Animals/dogs/Boston_terrier/1.png',
      'images/Animals/dogs/Boston_terrier/2.png',
      'images/Animals/dogs/Boston_terrier/3.png',
      'images/Animals/dogs/Boston_terrier/4.png',
      'images/Animals/dogs/Boston_terrier/5.png',
      'images/Animals/dogs/Boston_terrier/6.png',
    ],
    description: 'uma raça mt topzeira',
    cor: const Color.fromARGB(255, 46, 235, 209),
  ),
  PetsAdoptModel(
    name: 'Max',
    location: '2.9 Kms away',
    race: 'Siberian Husky',
    age: '1 year old',
    sex: 'Male',
    photos: [
      'images/Animals/dogs/Siberian_husky/1.png',
      'images/Animals/dogs/Siberian_husky/2.png',
      'images/Animals/dogs/Siberian_husky/3.png',
      'images/Animals/dogs/Siberian_husky/4.png',
      'images/Animals/dogs/Siberian_husky/5.png',
      'images/Animals/dogs/Siberian_husky/6.png',
    ],
    description: 'uma raça mt topzeira',
    cor: const Color.fromARGB(255, 93, 177, 255),
  ),
  PetsAdoptModel(
    name: 'Daisy',
    location: '2.5 Kms away',
    race: 'Maltese',
    age: '7 months old',
    sex: 'Female',
    photos: [
      'images/Animals/dogs/Maltese/1.png',
      'images/Animals/dogs/Maltese/2.png',
      'images/Animals/dogs/Maltese/3.png',
      'images/Animals/dogs/Maltese/4.png',
      'images/Animals/dogs/Maltese/5.png',
      'images/Animals/dogs/Maltese/6.png',
    ],
    description: 'uma raça mt topzeira',
    cor: const Color.fromARGB(255, 253, 173, 107),
  ),
  PetsAdoptModel(
    name: 'Zoe',
    location: '2.5 Kms away',
    race: 'Jack Russell terrier',
    age: '9 months old',
    sex: 'Female',
    photos: [
      'images/Animals/dogs/Jack_russell_terrier/1.png',
      'images/Animals/dogs/Jack_russell_terrier/2.png',
      'images/Animals/dogs/Jack_russell_terrier/3.png',
      'images/Animals/dogs/Jack_russell_terrier/4.png',
    ],
    description: 'uma raça mt topzeira',
    cor: const Color.fromARGB(255, 128, 228, 141),
  ),
];
